/**
 * Fastino README / tutorial / blog examples, adapted to the entity head
 * this ONNX graph actually runs ([E] queries). Classification ([C]),
 * relation ([R] / JointIE), and record-mode JSON are listed as `blocked`
 * so the page can show the original example without pretending it ran.
 */

export const PRESETS = [
  {
    id: "ner-card",
    group: "NER",
    title: "Model card",
    view: "entities",
    labels: "company, person, product, location",
    text: "Apple CEO Tim Cook announced iPhone 15 in Cupertino yesterday.",
  },
  {
    id: "ner-tutorial",
    group: "NER",
    title: "Tutorial (with date)",
    view: "entities",
    labels: "company, person, product, location, date",
    text: "Apple Inc. CEO Tim Cook announced the new iPhone 15 in Cupertino, California on September 12, 2023.",
  },
  {
    id: "ner-founders",
    group: "NER",
    title: "Multiple people",
    view: "entities",
    labels: "person, organization",
    text: "Bill Gates and Steve Jobs founded Microsoft and Apple respectively.",
  },
  {
    id: "ner-fr",
    group: "NER",
    title: "French (use multi)",
    view: "entities",
    suggestModel: "multi",
    labels: "personne, organisation, lieu, produit",
    text: "Timothée Chalamet a présenté Dune à Cannes avec Warner Bros.",
  },
  {
    id: "medical-desc",
    group: "Domain",
    title: "Clinical + descriptions",
    view: "entities",
    labels: "medication, dosage, symptom, time",
    descriptions: {
      medication: "Names of drugs, medications, or pharmaceutical substances",
      dosage: "Specific amounts like '400mg', '2 tablets', or '5ml'",
      symptom: "Medical symptoms, conditions, or patient complaints",
      time: "Time references like '2 PM', 'morning', or 'after lunch'",
    },
    text: "Patient received 400mg ibuprofen for severe headache at 2 PM.",
  },
  {
    id: "medical-tutorial",
    group: "Domain",
    title: "Metformin note",
    view: "entities",
    labels: "drug, disease, symptom, dosage, organ",
    descriptions: {
      drug: "Pharmaceutical drugs, medications, or treatment names",
      disease: "Medical conditions, illnesses, or disorders",
      symptom: "Clinical symptoms or patient-reported symptoms",
      dosage: "Medication amounts like '50mg' or '2 tablets daily'",
      organ: "Body parts or organs mentioned in medical context",
    },
    text: "Patient was prescribed Metformin 500mg twice daily for Type 2 Diabetes. She reported fatigue and occasional dizziness. Liver function tests ordered.",
  },
  {
    id: "legal",
    group: "Domain",
    title: "Legal",
    view: "entities",
    labels: "party, law_firm, court, statute, case, judge, legal_term",
    descriptions: {
      party: "Parties involved in legal proceedings (plaintiff, defendant, etc.)",
      law_firm: "Law firm or legal practice names",
      court: "Court names or judicial bodies",
      statute: "Legal statutes, laws, or regulations cited",
      case: "Legal case names or citations",
      judge: "Names of judges or magistrates",
      legal_term: "Legal terminology or concepts",
    },
    text: "In the case of Smith v. Jones, Judge Sarah Williams of the Superior Court ruled that the defendant violated Section 15.2 of the Consumer Protection Act. The plaintiff was represented by Miller & Associates.",
  },
  {
    id: "finance",
    group: "Domain",
    title: "Markets",
    view: "entities",
    labels: "ticker, financial_metric, currency_amount, percentage, financial_org, market_index",
    descriptions: {
      ticker: "Stock ticker symbols (e.g., AAPL, GOOGL)",
      financial_metric: "Financial metrics like P/E ratio, market cap",
      currency_amount: "Monetary values with currency symbols",
      percentage: "Percentage values (e.g., 5.2%, -3%)",
      financial_org: "Banks, investment firms, financial institutions",
      market_index: "Stock market indices (S&P 500, NASDAQ, etc.)",
    },
    text: "AAPL rose 3.5% to $185.50 after beating earnings expectations. The company's P/E ratio of 28.5 attracted Goldman Sachs analysts. The NASDAQ composite gained 1.2% for the day.",
  },
  {
    id: "science",
    group: "Domain",
    title: "Scientific",
    view: "entities",
    labels: "chemical, organism, gene, measurement, research_method, institution",
    descriptions: {
      chemical: "Chemical compounds or elements",
      organism: "Biological organisms, species names",
      gene: "Gene names or identifiers",
      measurement: "Scientific measurements with units",
      research_method: "Research techniques or methodologies",
      institution: "Universities or research institutions",
    },
    text: "Researchers at MIT discovered that the BRCA1 gene mutation increases cancer risk by 70%. The study used CRISPR-Cas9 to modify DNA sequences in Mus musculus specimens, measuring tumor growth in millimeters.",
  },
  {
    id: "json-product",
    group: "Structure",
    title: "Product fields",
    view: "json",
    parent: "product",
    labels: "name, price, features",
    strFields: ["name"],
    text: "The MacBook Pro costs $1999 and features M3 chip, 16GB RAM, and 512GB storage.",
  },
  {
    id: "json-iphone",
    group: "Structure",
    title: "iPhone 15 Pro Max",
    view: "json",
    parent: "product",
    labels: "name, storage, processor, price, colors",
    strFields: ["name", "storage", "processor", "price"],
    text: "iPhone 15 Pro Max with 256GB storage, A17 Pro chip, priced at $1199. Available in titanium and black colors.",
  },
  {
    id: "json-contact",
    group: "Structure",
    title: "Contact card",
    view: "json",
    parent: "contact",
    labels: "name, email, phone, address",
    strFields: ["name", "email", "address"],
    validators: {
      email: { pattern: "^[\\w.-]+@[\\w.-]+\\.\\w+$", mode: "full" },
    },
    text: "Contact: John Smith\nEmail: john@example.com\nPhones: 555-1234, 555-5678\nAddress: 123 Main St, NYC",
  },
  {
    id: "json-trade",
    group: "Structure",
    title: "Equity trade",
    view: "json",
    parent: "transaction",
    labels: "broker, amount, security, date, commission, status, type",
    strFields: ["broker", "amount", "security", "date", "commission", "status", "type"],
    text: "Transaction Report: Goldman Sachs processed a $2.5M equity trade for Tesla Inc. on March 15, 2024. Commission: $1,250. Status: Completed.",
  },
  {
    id: "json-rx",
    group: "Structure",
    title: "Prescriptions",
    view: "json",
    parent: "prescription",
    labels: "medication, dosage, frequency, name, age, symptoms",
    text: "Patient: Sarah Johnson, 34, presented with acute chest pain and shortness of breath. Prescribed: Lisinopril 10mg daily, Metoprolol 25mg twice daily. Follow-up scheduled for next Tuesday.",
  },
  {
    id: "json-event",
    group: "Structure",
    title: "Conference",
    view: "json",
    parent: "event",
    labels: "name, date, location, topics, registration_fee",
    strFields: ["name", "date", "location", "registration_fee"],
    text: "Tech Conference 2024 on June 15th in San Francisco. Topics include AI, Machine Learning, and Cloud Computing. Registration fee: $299 for early bird tickets.",
  },
  {
    id: "kg-spacex",
    group: "Knowledge graph",
    title: "SpaceX (README)",
    view: "graph",
    labels: "person, organization, location, date",
    text: "Elon Musk founded SpaceX in 2002. SpaceX is located in Hawthorne, California. SpaceX acquired Swarm Technologies in 2021. Many engineers work for SpaceX.",
  },
  {
    id: "kg-blog",
    group: "Knowledge graph",
    title: "Cook / Pichai (blog)",
    view: "graph",
    labels: "person, organization, location",
    text: "Tim Cook leads Apple in Cupertino. Sundar Pichai runs Google in Mountain View.",
  },
  {
    id: "kg-org",
    group: "Knowledge graph",
    title: "Org chart text",
    view: "graph",
    labels: "person, organization, location",
    text: "John works for Apple Inc. and lives in San Francisco. Apple Inc. is located in Cupertino. Sarah founded TechCorp in 2020. She is married to Mike, who works at Google. TechCorp is located in Seattle.",
  },
  {
    id: "pii",
    group: "PII",
    title: "Redact contacts",
    view: "redact",
    labels: "person, email, phone, address",
    validators: {
      email: { pattern: "[\\w.-]+@[\\w.-]+\\.\\w+", mode: "partial" },
    },
    text: "Contact John Doe at john.doe@email.com or call (555) 123-4567. Mail goes to 14 Rue des Écoles, 75005 Paris.",
  },
  {
    id: "span-long",
    group: "Long span",
    title: "Whole clause",
    view: "entities",
    labels: "party, clause, obligation, duration, notice",
    text: "Indemnification. TechCorp LLC shall indemnify, defend, and hold harmless DataSystems Inc., its officers, directors, employees, and agents from and against any and all claims, damages, losses, and expenses, including reasonable attorneys' fees, arising out of or resulting from the performance of services under this Agreement, except to the extent caused by the indemnified party's gross negligence or willful misconduct.",
  },
  {
    id: "span-address",
    group: "Long span",
    title: "Full address",
    view: "entities",
    labels: "organization, full_address, person",
    descriptions: {
      full_address: "Complete postal address including street, city, region, and postal code as a single span",
    },
    text: "Please ship the replacement unit to Acme Robotics, 1600 Amphitheatre Parkway, Mountain View, California 94043, attention Maya Chen.",
  },
  {
    id: "long-doc",
    group: "Long context",
    title: "Short contract (chunked)",
    view: "entities",
    chunkSize: 48,
    chunkOverlap: 12,
    labels: "company, date, duration, fee, obligation",
    text: "Service Agreement between TechCorp LLC and DataSystems Inc., effective January 1, 2024. Monthly fee: $15,000. Contract term: 24 months with automatic renewal. Termination clause: 30-day written notice required. TechCorp LLC shall provide managed infrastructure monitoring across production and staging. DataSystems Inc. shall pay invoices within fifteen days. Neither party may assign this agreement without prior written consent. Governing law is the State of Delaware. Notices shall be sent to the registered offices of both parties. This paragraph exists so the demo actually splits the document into overlapping word chunks and remaps every span back to the original character offsets.",
  },
  {
    id: "attr-product",
    group: "Attributes",
    title: "Product + sentiment overlay",
    view: "entities",
    labels: "product, positive, negative, neutral",
    note: "Span attributes in Python are a second decode on the same pass. Here positive/negative/neutral are extra [E] labels; the page attaches the overlapping one to each product.",
    text: "The iPhone camera is stunning but the battery life is disappointing, while the speakers are fine.",
  },
  {
    id: "cls-sentiment",
    group: "Not in this graph",
    title: "Classification (blocked)",
    blocked: "classify",
    labels: "product, feature",
    text: "This laptop has amazing performance but terrible battery life!",
    note: "classify_text / constrained classification uses [C] queries and a classification head. Not in this ONNX graph. Entity fallback: product/feature spans.",
  },
  {
    id: "rel-blocked",
    group: "Not in this graph",
    title: "extract_relations (blocked)",
    blocked: "relations",
    view: "graph",
    labels: "person, organization, location",
    text: "John works for Apple Inc. and lives in San Francisco. Apple Inc. is located in Cupertino.",
    note: "Typed edges need JointIE / the [R] relation head. Python extract_relations on this 2.5 checkpoint returned empty on the blog example. This page draws co-mention links between entities in the same sentence, which is not JointIE.",
  },
];
