/**
 * Fastino README / tutorial / 2.5 blog examples.
 * `group` drives the page sections. `source` is a small chip tag.
 * `view` selects the result pane: entities | json | graph | classify | redact.
 */

export const GROUPS = [
  {
    id: "NER",
    title: "Named entities",
    blurb: "Zero-shot [E] labels. Same head as the model card.",
  },
  {
    id: "Domain",
    title: "Domain NER",
    blurb: "Labels plus [DESCRIPTION] text folded into the parent token.",
  },
  {
    id: "Structure",
    title: "Structured fields",
    blurb: "Field-as-label JSON. Same [E] queries under a parent name (product, contact, …).",
  },
  {
    id: "Records",
    title: "Repeated records",
    blurb: "Natural RecordHead: first declared field seeds instances; records.onnx assigns the rest. Same messy fields as Python.",
  },
  {
    id: "Relations",
    title: "Typed relations (JointIE)",
    blurb: "Entity decode, then the [R] scorer + JS beam. Edges are typed, not co-mention.",
  },
  {
    id: "Classification",
    title: "Classification",
    blurb: "classify_text is one shot (WebGPU base/multi die ~3500 words). Long contract uses classify_text_long: 384/64 windows, max-confidence chunk.",
  },
  {
    id: "PII",
    title: "PII / redaction",
    blurb: "Entity labels, then the page masks the spans.",
  },
  {
    id: "Long span",
    title: "Long spans",
    blurb: "Span-free decode: a whole clause costs the same as a two-word name.",
  },
  {
    id: "Long context",
    title: "Long documents",
    blurb: "extract_entities_long / classify_text_long: 384-word windows, overlap 64. Not a 4096-word GPU run. Python one-shot max_len is 4096; WebGPU base/multi crash before that.",
  },
  {
    id: "Attributes",
    title: "Span attributes",
    blurb: "Python packs product + attribute labels in one [E] pass, then softmax on score_explicit_spans. A product-only pass keeps a shorter span.",
  },
];

export const PRESETS = [
  {
    id: "ner-card",
    group: "NER",
    source: "card",
    title: "Apple / Cook",
    view: "entities",
    labels: "company, person, product, location",
    text: "Apple CEO Tim Cook announced iPhone 15 in Cupertino yesterday.",
  },
  {
    id: "ner-tutorial",
    group: "NER",
    source: "tutorial",
    title: "With date",
    view: "entities",
    labels: "company, person, product, location, date",
    text: "Apple Inc. CEO Tim Cook announced the new iPhone 15 in Cupertino, California on September 12, 2023.",
  },
  {
    id: "ner-founders",
    group: "NER",
    source: "tutorial",
    title: "Two founders",
    view: "entities",
    labels: "person, organization",
    text: "Bill Gates and Steve Jobs founded Microsoft and Apple respectively.",
  },
  {
    id: "ner-fr",
    group: "NER",
    source: "demo",
    title: "French (multi)",
    view: "entities",
    suggestModel: "multi",
    labels: "personne, organisation, lieu, produit",
    text: "Timothée Chalamet a présenté Dune à Cannes avec Warner Bros.",
  },
  {
    id: "medical-desc",
    group: "Domain",
    source: "tutorial",
    title: "Clinical",
    view: "entities",
    labels: "medication, dosage, symptom, time",
    descriptions: {
      medication: "Names of drugs, medications, or pharmaceutical substances",
      dosage: "Specific amounts like '400mg', '2 tablets', or '5ml'",
      symptom: "Medical symptoms, conditions, or patient complaints",
      time: "Time references like '2 PM', 'morning', or 'after lunch'",
    },
    text: "Patient received 400mg ibuprofen for severe headache at 2 PM.",
  },
  {
    id: "medical-tutorial",
    group: "Domain",
    source: "tutorial",
    title: "Metformin note",
    view: "entities",
    labels: "drug, disease, symptom, dosage, organ",
    descriptions: {
      drug: "Pharmaceutical drugs, medications, or treatment names",
      disease: "Medical conditions, illnesses, or disorders",
      symptom: "Clinical symptoms or patient-reported symptoms",
      dosage: "Medication amounts like '50mg' or '2 tablets daily'",
      organ: "Body parts or organs mentioned in medical context",
    },
    text: "Patient was prescribed Metformin 500mg twice daily for Type 2 Diabetes. She reported fatigue and occasional dizziness. Liver function tests ordered.",
  },
  {
    id: "legal",
    group: "Domain",
    source: "tutorial",
    title: "Legal",
    view: "entities",
    labels: "party, law_firm, court, statute, case, judge, legal_term",
    descriptions: {
      party: "Parties involved in legal proceedings (plaintiff, defendant, etc.)",
      law_firm: "Law firm or legal practice names",
      court: "Court names or judicial bodies",
      statute: "Legal statutes, laws, or regulations cited",
      case: "Legal case names or citations",
      judge: "Names of judges or magistrates",
      legal_term: "Legal terminology or concepts",
    },
    text: "In the case of Smith v. Jones, Judge Sarah Williams of the Superior Court ruled that the defendant violated Section 15.2 of the Consumer Protection Act. The plaintiff was represented by Miller & Associates.",
  },
  {
    id: "finance",
    group: "Domain",
    source: "tutorial",
    title: "Markets",
    view: "entities",
    labels: "ticker, financial_metric, currency_amount, percentage, financial_org, market_index",
    descriptions: {
      ticker: "Stock ticker symbols (e.g., AAPL, GOOGL)",
      financial_metric: "Financial metrics like P/E ratio, market cap",
      currency_amount: "Monetary values with currency symbols",
      percentage: "Percentage values (e.g., 5.2%, -3%)",
      financial_org: "Banks, investment firms, financial institutions",
      market_index: "Stock market indices (S&P 500, NASDAQ, etc.)",
    },
    text: "AAPL rose 3.5% to $185.50 after beating earnings expectations. The company's P/E ratio of 28.5 attracted Goldman Sachs analysts. The NASDAQ composite gained 1.2% for the day.",
  },
  {
    id: "science",
    group: "Domain",
    source: "tutorial",
    title: "Scientific",
    view: "entities",
    labels: "chemical, organism, gene, measurement, research_method, institution",
    descriptions: {
      chemical: "Chemical compounds or elements",
      organism: "Biological organisms, species names",
      gene: "Gene names or identifiers",
      measurement: "Scientific measurements with units",
      research_method: "Research techniques or methodologies",
      institution: "Universities or research institutions",
    },
    text: "Researchers at MIT discovered that the BRCA1 gene mutation increases cancer risk by 70%. The study used CRISPR-Cas9 to modify DNA sequences in Mus musculus specimens, measuring tumor growth in millimeters.",
  },
  {
    id: "json-product",
    group: "Structure",
    source: "readme",
    title: "MacBook Pro",
    view: "json",
    parent: "product",
    labels: "name, price, features",
    strFields: ["name"],
    text: "The MacBook Pro costs $1999 and features M3 chip, 16GB RAM, and 512GB storage.",
  },
  {
    id: "json-iphone",
    group: "Structure",
    source: "tutorial",
    title: "iPhone 15 Pro Max",
    view: "json",
    parent: "product",
    labels: "name, storage, processor, price, colors",
    strFields: ["name", "storage", "processor", "price"],
    text: "iPhone 15 Pro Max with 256GB storage, A17 Pro chip, priced at $1199. Available in titanium and black colors.",
  },
  {
    id: "json-contact",
    group: "Structure",
    source: "tutorial",
    title: "Contact card",
    view: "json",
    parent: "contact",
    labels: "name, email, phone, address",
    strFields: ["name", "email", "address"],
    validators: {
      email: { pattern: "^[\\w.-]+@[\\w.-]+\\.\\w+$", mode: "full" },
    },
    text: "Contact: John Smith\nEmail: john@example.com\nPhones: 555-1234, 555-5678\nAddress: 123 Main St, NYC",
  },
  {
    id: "json-trade",
    group: "Structure",
    source: "tutorial",
    title: "Equity trade",
    view: "json",
    parent: "transaction",
    labels: "broker, amount, security, date, commission, status, type",
    strFields: ["broker", "amount", "security", "date", "commission", "status", "type"],
    text: "Transaction Report: Goldman Sachs processed a $2.5M equity trade for Tesla Inc. on March 15, 2024. Commission: $1,250. Status: Completed.",
  },
  {
    id: "json-event",
    group: "Structure",
    source: "tutorial",
    title: "Conference",
    view: "json",
    parent: "event",
    labels: "name, date, location, topics, registration_fee",
    strFields: ["name", "date", "location", "registration_fee"],
    text: "Tech Conference 2024 on June 15th in San Francisco. Topics include AI, Machine Learning, and Cloud Computing. Registration fee: $299 for early bird tickets.",
  },
  {
    id: "json-rx",
    group: "Records",
    source: "tutorial",
    title: "Two prescriptions",
    view: "json",
    records: true,
    note: "Natural RecordHead: first str field seeds instances; records.onnx assigns the rest (null column).",
    parent: "prescription",
    labels: "medication, dosage, frequency, name, age",
    strFields: ["name", "age"],
    text: "Patient: Sarah Johnson, 34, presented with acute chest pain and shortness of breath. Prescribed: Lisinopril 10mg daily, Metoprolol 25mg twice daily. Follow-up scheduled for next Tuesday.",
  },
  {
    id: "kg-spacex",
    group: "Relations",
    source: "readme",
    title: "SpaceX",
    view: "graph",
    labels: "person, organization, location, date",
    relations: {
      founded: { head: ["person"], tail: ["organization"], unique_head: true },
      located_in: { head: ["organization"], tail: ["location"], unique_head: true },
      acquired: { head: ["organization"], tail: ["organization"] },
      works_for: { head: ["person"], tail: ["organization"], unique_head: true },
    },
    text: "Elon Musk founded SpaceX in 2002. SpaceX is located in Hawthorne, California. SpaceX acquired Swarm Technologies in 2021. Many engineers work for SpaceX.",
  },
  {
    id: "kg-blog",
    group: "Relations",
    source: "blog",
    title: "Cook / Pichai",
    view: "graph",
    labels: "person, organization, location",
    relations: {
      leads: { head: ["person"], tail: ["organization"], unique_head: true },
      located_in: { head: ["organization"], tail: ["location"], unique_head: true },
    },
    text: "Tim Cook leads Apple in Cupertino. Sundar Pichai runs Google in Mountain View.",
  },
  {
    id: "kg-org",
    group: "Relations",
    source: "tutorial",
    title: "Org chart",
    view: "graph",
    labels: "person, organization, location",
    relations: {
      works_for: { head: ["person"], tail: ["organization"], unique_head: true },
      lives_in: { head: ["person"], tail: ["location"], unique_head: true },
      located_in: { head: ["organization"], tail: ["location"], unique_head: true },
      founded: { head: ["person"], tail: ["organization"], unique_head: true },
      married_to: { head: ["person"], tail: ["person"], allowSelf: false, unique_head: true, unique_tail: true },
    },
    text: "John works for Apple Inc. and lives in San Francisco. Apple Inc. is located in Cupertino. Sarah founded TechCorp in 2020. She is married to Mike, who works at Google. TechCorp is located in Seattle.",
  },
  {
    id: "cls-sentiment",
    group: "Classification",
    source: "readme",
    title: "Sentiment",
    view: "classify",
    task: "sentiment",
    labels: "positive, negative, neutral",
    text: "This laptop has amazing performance but terrible battery life!",
  },
  {
    id: "cls-intent",
    group: "Classification",
    source: "tutorial",
    title: "Intent",
    view: "classify",
    task: "intent",
    labels: "read, write, delete",
    text: "Delete the temporary file from /tmp",
  },
  {
    id: "cls-constrained",
    group: "Classification",
    source: "readme",
    title: "Implies / excludes",
    view: "classify",
    labels: "positive, negative, neutral",
    tasks: {
      sentiment: { labels: ["positive", "negative", "neutral"] },
      urgency: { labels: ["urgent", "not_urgent"] },
    },
    implies: { "urgency:urgent": ["sentiment:negative"] },
    excludes: { "sentiment:positive": ["sentiment:negative"] },
    text: "Cancel this order immediately. The device is defective and I want a refund today.",
    note: "JS beam over cls_logits with implies/excludes. urgent implies negative; positive excludes negative.",
  },
  {
    id: "cls-long",
    group: "Classification",
    source: "long",
    title: "Long contract",
    view: "classify",
    long: true,
    task: "topic",
    labels: "technology, business, legal, sports",
    note: "classify_text_long, not classify_text. 384-word windows, overlap 64, keep the highest-confidence chunk. A 4096-word file would be 13 GPU runs of 384 words. WebGPU one-shot on base/multi dies around 3500 words.",
    text: "MASTER SERVICES AGREEMENT between Helios Robotics OÜ (\"Provider\") and Northwind Data GmbH (\"Customer\"), effective 1 March 2026. Provider shall supply managed inference infrastructure, model-hosting capacity, and on-call incident response for Customer's document-processing workloads. Fees are fifteen thousand euros per month, invoiced in arrears, payable within fifteen days. The term is twenty-four months with automatic renewal for successive twelve-month periods unless either party gives ninety days written notice. Governing law is the law of Estonia. Disputes shall be resolved in the courts of Tallinn. Provider shall maintain professional indemnity insurance of not less than one million euros. Customer shall not reverse engineer hosted models. Confidential information excludes information that is public, independently developed, or required by law to be disclosed. Notices go to the registered offices. Neither party may assign this agreement without prior written consent, except to an affiliate. Force majeure covers war, flood, epidemic, and failure of public networks. If a clause is unenforceable the remainder survives. This agreement is the entire agreement and supersedes all prior proposals. Amendments must be in writing and signed. The parties have executed this agreement as of the date first written above. Schedule A lists the environments: production in Frankfurt, staging in Amsterdam, and a disaster-recovery replica in Stockholm. Schedule B lists the service levels: 99.9 percent monthly uptime, a fifteen-minute acknowledge target for severity-one incidents, and a four-hour restore target. Customer data remains Customer data. Provider processes it only on documented instructions. Subprocessors are named in Schedule C and may change on thirty days notice. Audit rights are once per year on reasonable notice. Upon termination Provider shall delete Customer data within thirty days unless law requires retention. The indemnification clause covers third-party intellectual-property claims arising from Provider software, except to the extent caused by Customer materials. Limitation of liability is twelve months of fees, excluding fraud, death, or personal injury. Liquidated damages for missed uptime are a service-credit schedule, not a penalty. Export-control warranties apply. The parties acknowledge they have had opportunity to take legal advice. Signatures follow on the next page. Additional operating clauses: change management requires a ticket, a rollback plan, and a maintenance window outside European business hours. Security reviews occur quarterly. Penetration tests are annual. Backup restoration is tested twice a year. On-call rotations are published a month in advance. Status pages shall not name Customer. Marketing references require written approval. Open-source notices ship with each release. Training data for fine-tunes is Customer's to license. Model cards stay with the artifacts. These operating clauses exist so the page must split the document into overlapping word windows rather than classifying a single short paragraph.",
  },
  {
    id: "pii",
    group: "PII",
    source: "tutorial",
    title: "Redact contacts",
    view: "redact",
    labels: "person, email, phone, address",
    validators: {
      email: { pattern: "[\\w.-]+@[\\w.-]+\\.\\w+", mode: "partial" },
    },
    text: "Contact John Doe at john.doe@email.com or call (555) 123-4567. Mail goes to 14 Rue des Écoles, 75005 Paris.",
  },
  {
    id: "span-long",
    group: "Long span",
    source: "blog",
    title: "Whole clause",
    view: "entities",
    labels: "party, clause, obligation, duration, notice",
    text: "Indemnification. TechCorp LLC shall indemnify, defend, and hold harmless DataSystems Inc., its officers, directors, employees, and agents from and against any and all claims, damages, losses, and expenses, including reasonable attorneys' fees, arising out of or resulting from the performance of services under this Agreement, except to the extent caused by the indemnified party's gross negligence or willful misconduct.",
  },
  {
    id: "span-address",
    group: "Long span",
    source: "blog",
    title: "Full address",
    view: "entities",
    labels: "organization, full_address, person",
    descriptions: {
      full_address: "Complete postal address including street, city, region, and postal code as a single span",
    },
    text: "Please ship the replacement unit to Acme Robotics, 1600 Amphitheatre Parkway, Mountain View, California 94043, attention Maya Chen.",
  },
  {
    id: "long-doc",
    group: "Long context",
    source: "tutorial",
    title: "Chunked contract",
    view: "entities",
    chunkSize: 48,
    chunkOverlap: 12,
    labels: "company, date, duration, fee, obligation",
    text: "Service Agreement between TechCorp LLC and DataSystems Inc., effective January 1, 2024. Monthly fee: $15,000. Contract term: 24 months with automatic renewal. Termination clause: 30-day written notice required. TechCorp LLC shall provide managed infrastructure monitoring across production and staging. DataSystems Inc. shall pay invoices within fifteen days. Neither party may assign this agreement without prior written consent. Governing law is the State of Delaware. Notices shall be sent to the registered offices of both parties. This paragraph exists so the demo actually splits the document into overlapping word chunks and remaps every span back to the original character offsets.",
  },
  {
    id: "attr-product",
    group: "Attributes",
    source: "blog",
    title: "Product sentiment",
    view: "attributes",
    labels: "product",
    attributeLabels: "positive, negative, neutral",
    note: "Joint [E] pack (product + sentiment labels), then attrs.onnx softmax. 512-word local window, not a document cap.",
    text: "The iPhone camera is stunning but the battery life is disappointing, while the speakers are fine.",
  },
];
